[theme]
# Set the base mode to dark
base="dark" 
# A custom primary accent color (e.g., Streamlit Blue)
primaryColor="#FF4B4B" 
# The main app background
backgroundColor="#0E1117" 
# Sidebar and input widgets background
secondaryBackgroundColor="#262730" 
# Default font family
font="sans serif" 
